local recs = {}

-- 1997
recs["Demo Level #1"] = 1
recs["Demo Level #2"] = 1
recs["Dog-Gone Fort Adventure"] = 1
-- 1998
recs["Curse of Tiger Island"] = 1
recs["Odyssey to the Battlements"] = 1
recs["Cavern of Terror"] = 1
recs["Sailing Tward Antarctica"] = 1
recs["Across the Frozen Planes"] = 1
recs["Will Rulz"] = 1
recs["Merlin's Mansion"] = 1
recs["Demon's Isle"] = 1
-- 1999
recs["Fort Raltinia"] = 1
recs["Pine Valley"] = 1
recs["Tropicalia Island"] = 1
recs["Flying Carpet Ride"] = 2
recs["Admiral Le Rauxe's Fort"] = 1
-- 2000
recs["Mother of All Caverns"] = 2
recs["Claw Junior 1"] = 1
recs["Claw Junior 5"] = 1
recs["UnderSea World"] = 2
recs["Fim da Floresta"] = 1
-- 2001
recs["Mommy of All Caverns"] = 2
recs["Lanka Dahan - The Fall of Gabriel"] = 1
recs["Through The Jungle"] = 1
recs["The Cliffs of Death"] = 1
recs["Red Tail's Hideout"] = 2
recs["Trilha do Claw"] = 1
recs["One Man Assault 2"] = 2
-- 2002
recs["Treasure Island"] = 2
-- 2003
recs["Claw's Jungle Adventure"] = 1
recs["Huggerland"] = 1
-- 2004
recs["Treasure Hunt"] = 1
recs["Deeper Caves Part 1"] = 1
recs["La Roca's Wrath"] = 1
recs["DzjeeAr"] = 2
recs["Gabriel's Shipyard"] = 1
recs["Tropical Paradise"] = 2
recs["Edd Brown 10"] = 1
recs["The Mysteries of the Pier"] = 1
recs["Claw in the Cavern's Heart"] = 1
recs["Battle Fortress"] = 1
recs["Small Ville"] = 1
recs["War of the Dogs"] = 1
recs["Deepest Halls of Terror"] = 2
-- 2005
recs["Remora Bay"] = 1
recs["Claw be Jammed!"] = 2
recs["Canyon Refuge"] = 2
recs["Stenchburg"] = 1
recs["Fawlty Towers"] = 2
recs["Seaside Town v1.1"] = 1
recs["La Roca's Secrets"] = 1
recs["Docks at Night v1.1"] = 1
recs["Le Rauxe's Fort v1.1"] = 1
recs["Straggle"] = 1
recs["Claw Armageddon"] = 1
recs["Escape"] = 1
recs["River Race Revised"] = 2
recs["Find Final Gem"] = 1
-- 2006
recs["RORT Part 1 -- The Barracks"] = 2
recs["RORT Part 2 -- The Construction Zone"] = 2
recs["RORT Part 3 -- The Mines"] = 2
recs["RORT Part 4 -- Omar's Last Stand"] = 2
recs["RORT Part 5 -- Payback Time"] = 2
recs["Encounter in the Deep"] = 2
recs["Death Path v1.1"] = 2
recs["Blackout v2.0"] = 2
recs["Crystal Caverns v1.1"] = 2
recs["The Treason of Katherine"] = 2
recs["Dark Paths"] = 1
recs["Cross Country v1.2"] = 1
recs["The River of Boiling Blood"] = 2
recs["Palace of Zin"] = 2
recs["Escape To Freedom"] = 1
-- 2007
recs["Peutro Lobo"] = 1
recs["Castle"] = 1
recs["Clearing"] = 1
recs["Swamp Camp v1.1"] = 1
recs["Follow the Clues"] = 1
recs["The Guantatraz Prison"] = 1
recs["Pirates' Beach"] = 1
recs["Tiger's Temple"] = 1
recs["Big Beer"] = 1
recs["Summer Time"] = 1
recs["Remora Harbor"] = 1
recs["The Palace"] = 1
recs["Way"] = 1
recs["Picnic with Claw"] = 1
recs["Prison Raux"] = 1
recs["Siege Cat v1.1"] = 1
recs["Twilight Coast"] = 2
recs["The Wind Tunnels"] = 2
recs["Abyss of Cultists v1.1"] = 2
recs["Caves on Tiger Island"] = 1
recs["Secrets of Tiger Island"] = 2
recs["Lethal Walls v1.1"] = 1
recs["The Cave of the Mysteries"] = 1
recs["The Forest Curse"] = 1
recs["High Noon"] = 2
recs["Blood City"] = 1
recs["Prison Break"] = 2
recs["Defeating La Roca's Guards"] = 1
recs["God of War"] = 2
recs["Walking in the Dark"] = 1
recs["Shadow of Death Valley"] = 2
recs["Dangerous Footpath"] = 1
recs["Imperial Castle"] = 1
recs["Shores of Mist"] = 1
recs["Broken Bay"] = 1
recs["Terras Turquoise"] = 1
recs["Village Passage"] = 2
recs["The Endless Castle"] = 1
recs["Kingdom of Treasure"] = 1
recs["The Devilish Tower"] = 1
recs["Tide Time"] = 2
recs["The Mystic Forest"] = 1
recs["I Love Claw!"] = 2
recs["City After Party"] = 1
recs["The Beach"] = 1
recs["Assassin"] = 2
recs["Secret Lake"] = 1
recs["Captain Claw and the Petrified Forest"] = 2
recs["The Villa"] = 1
recs["Escape To Freedom (Re-Edit)"] = 1
recs["Dungeons of Darkness"] = 1
recs["Claw 10"] = 1
recs["Wood Castle v2.0"] = 1
recs["Ghost Ship"] = 1
recs["Broadsides"] = 2
recs["Small Town"] = 1
recs["Small Town v2.0"] = 1
-- 2008
recs["Echoing Tunnel v1.1"] = 2
recs["Secret Cavern"] = 1
recs["Lost"] = 1
recs["Le Rauxe's Citadel"] = 1
recs["Poor Streets v1.2"] = 2
recs["Mystery of Shipyards"] = 1
recs["Piratical Isles"] = 1
recs["Kerala's Treasure"] = 2
recs["Lost in the Cliffs"] = 2
recs["Skulls' Coast"] = 1
recs["Thieves' Paradise"] = 1
recs["Historic Avenues"] = 1
recs["EXIT"] = 1
recs["The Great Earthquake"] = 1
recs["God of War - Part 2"] = 2
recs["Arrested"] = 2
recs["Claw Crash"] = 1
recs["Execution"] = 1
recs["Admiral Claw"] = 1
recs["The Everest"] = 1
recs["Officers' Fort"] = 1
recs["Doom"] = 2
recs["Crazy Level"] = 1
recs["Grand Maze"] = 2
recs["In Search of National Treasure"] = 2
recs["PULTZ3"] = 1
recs["3.00 AM"] = 1
recs["An Abyss of Despair"] = 1
recs["Cave of Shadows"] = 1
recs["Sewerouluss City"] = 2
recs["Green Town"] = 2
recs["Pirates' Hiding Place"] = 1
recs["Jungle"] = 2
recs["Wanted Claw"] = 1
recs["Temple Death"] = 1
recs["The Red Cave"] = 1
recs["Lake of Death"] = 1
recs["Zone Prison"] = 1
recs["Catacombs"] = 2
recs["Dark Castle v.2.0"] = 1
recs["The Best 3"] = 1
recs["Forest Crossroads"] = 1
recs["Edd Brown 1"] = 1
recs["The Underground Journey"] = 2
recs["Haunted House"] = 2
-- 2009
recs["The Sky v1.1"] = 2
recs["Wooden Castle"] = 1
recs["Halls of Lavafalls and Fireballs"] = 2
recs["Tajemnicza Dzungla"] = 2
recs["RocaEscape"] = 1
recs["Secret Place"] = 2
recs["Pyramyde"] = 1
recs["Edd Brown 2"] = 1
recs["Igneous Bluffs"] = 2
recs["Rivendells 1st Go"] = 1
recs["Return of Hitler"] = 1
recs["Rope Ladder Journey"] = 1
recs["Stone Field"] = 1
recs["Black Marsh"] = 1
recs["Devilish Village"] = 1
recs["Bushy Trip"] = 1
recs["Death!"] = 1
recs["Magic Village"] = 2
recs["Underwater Corridors"] = 1
recs["Big Cottage"] = 1
recs["Legend"] = 1
recs["Enterspace"] = 1
recs["Exile"] = 2
recs["Murky Dunes"] = 2
-- 2010
recs["11 Skeletons"] = 1
recs["Damp Place"] = 1
recs["Wreckage"] = 2
recs["Royal Chambers"] = 2
recs["Boiling Tar"] = 1
recs["Seismic Lair"] = 1
recs["Freight Boats"] = 2
recs["Narrow Nooks v2.0"] = 2
recs["Forgotten Caves of Undersea World"] = 2
recs["Claw's Mission"] = 1
recs["Room of Elevators"] = 1
recs["Town at Night"] = 1
recs["In the Hands of the Bandits"] = 1
recs["The Diamond Mines"] = 1
recs["Dark Dungeons"] = 1
recs["Orange Town"] = 1
recs["Escape from La Roca Part 2"] = 1
recs["Path of Fright"] = 1
-- 2011
recs["Mar del Plata Beach"] = 1
recs["A Deadly Struggle for Speed"] = 1
recs["Time of Heroic Challenges"] = 1
recs["Cannon Play"] = 2
recs["Jail"] = 1
recs["Fight Arena 14"] = 1
recs["Fetid Cave of Treasures"] = 1
recs["Fly to the Rung"] = 1
recs["Mysterious Forest"] = 1
recs["Roca Towers"] = 1
recs["A Chance to Run Away"] = 1
recs["1+14"] = 1
recs["Mount Everest"] = 1
recs["Stronghold"] = 2
recs["8+9"] = 2
recs["Suburbia"] = 1
recs["Dark Catacombs"] = 1
-- 2012
recs["The Trail of Geckos - Dungeons v2.0"] = 2
recs["Ciudad del Wolvington"] = 1
recs["Wolvington Hideout"] = 1
recs["Pixels v1.1"] = 1
recs["Dungeon Maze"] = 1
recs["Sunny Beach"] = 2
recs["Stargate to Paradise"] = 2
recs["El Dorado"] = 2
-- 2013
recs["La RockaRolla"] = 1
recs["The Dark Journey"] = 2
-- 2014
recs["Abandoned Mine"] = 2
recs["Horror"] = 2
recs["You and Whose Army!"] = 1
recs["The End"] = 1
-- 2015
recs["Zakrzywienie Czasu"] = 2
recs["Pandemonium"] = 1
recs["Infernal Chambers"] = 2
recs["Eisse Grotten"] = 1
recs["Column"] = 2
recs["Forest Town"] = 1
recs["Big Town's Secrets"] = 1
recs["Danger City"] = 1
-- 2016
recs["Bloodbath v2.1"] = 2
recs["Cast Away"] = 2
recs["Crabs Island"] = 1
recs["Creep Diving"] = 2
recs["Creep Diving Lite"] = 2
recs["A Closet Woodland"] = 1
recs["Prehistoric Cliffs"] = 1
recs["Marrow's Challenge v1.1"] = 1
recs["Climber"] = 2
recs["Nightshade Forests"] = 2
recs["4+2"] = 2
recs["13+3"] = 2
recs["Escape from Russia"] = 1
recs["Castle in the Clouds"] = 2
recs["Back to Revenge"] = 1
recs["Just Keep Calm"] = 2
recs["Trap Trails"] = 2
recs["The Peaceful Island"] = 1
recs["Small Refuge"] = 1
recs["Ready or Not"] = 1
recs["Palace on the Beach"] = 2
-- 2017
recs["Niagara Falls"] = 2
recs["Gattabuia"] = 2
recs["Azure Prison (11+1)"] = 2
recs["Pastureland"] = 2
recs["Prison Corridors"] = 1
recs["Golden Gate"] = 1
recs["Super Claw"] = 1
recs["Blackbeard's Cove"] = 2
-- 2018
recs["Run of the Tiger"] = 1
recs["Nowy Dzien"] = 2
recs["Poszukiwanie Amuletu"] = 2
recs["Forest of Hidden Treasures"] = 2
recs["The Nest of Pirates"] = 1
recs["12+14"] = 1
recs["CAFTA Part 13 - Meeting with Red Tail"] = 2
recs["Pre2Claw"] = 2
recs["Fizik Who 11"] = 1
recs["Adventure in Winter Land v0.4"] = 2
recs["Deathtrap District"] = 2
recs["Fizik Who 10"] = 1
recs["Midnight Fight"] = 2
recs["Deadly Trip"] = 2
recs["Hellzone"] = 2
recs["Hellzone - Easy Version"] = 2
recs["10+3"] = 2
recs["Canyon of Despair"] = 1
-- 2019
recs["Thieves' Trail"] = 2
recs["The Trail of Geckos - Dungeons v2.0"] = 2
recs["Fizik Who 13"] = 2
recs["Temple of Chameleons"] = 1
recs["Floating Islands of Wealth"] = 2
recs["Tropical Docks at Morning (7+12+13)"] = 2
recs["Stronghold Mk. 2"] = 2
recs["Claw Tower"] = 2
recs["Fizik Who 9"] = 2
recs["Nothing There v1.1"] = 2
recs["Rural Alleys of Death v2.0"] = 2
recs["Darkest Pirates' Lair v2.0"] = 2
recs["Valley of Caverns v2.0"] = 2
recs["Zuczek's (Not) Last Word"] = 2
recs["Tropical Tunnels"] = 2
recs["Secret Passages"] = 2
recs["Xmas with Claw"] = 2
recs["State of Siege"] = 2
-- 2020
recs["Wreckage 10th Anniversary Edition"] = 2
recs["Wreckage - 10th Anniversary Edition"] = 2
recs["Secret Tunnel to the Undersea Caves"] = 1
recs["Evolution of Shipyards"] = 1
recs["Toxic Waste"] = 2
recs["Towards the Core of the Volcano"] = 1
recs["Symmetric Level"] = 1
recs["Raid on the Spanish Armada"] = 2
recs["Earthy Grove"] = 2
recs["Party in Cliffs"] = 1
recs["Caves of Illusions"] = 2
recs["Mountain Camp"] = 1
recs["Quest of the Prisoner"] = 2
recs["Wild Harbor (Remake)"] = 2
recs["Littoral Forests of Tiger Island v2.0"] = 2
recs["Mystic Depths v2.0"] = 2
recs["Commandment of Thieves"] = 1
recs["Claw's Clone"] = 2
-- 2021
recs["Port of Pain"] = 2
recs["Forest of Treasures"] = 1
recs["Claw and the Castle"] = 1
recs["Claw and the Royal Trail"] = 1
recs["Claw in the Heart of the Forest"] = 1
recs["Claw and the Great Wall"] = 1
recs["Claw and the Village of Wolves"] = 1
recs["Claw in Downtown"] = 1
recs["Chaotic Catacombs"] = 2
recs["Night Wood v2.0"] = 2
recs["Claw Looking at the Moon"] = 2
recs["Castle at War v2.0"] = 2
recs["Murky Valley"] = 2
recs["Bricks"] = 2
recs["Total War"] = 2
recs["Birthday (short version)"] = 2
recs["Pirates' Lair"] = 2
recs["Through the Barricades"] = 1
recs["Invasion of Lumberjacks v2.0"] = 2
-- 2022
recs["Birthday"] = 2
recs["Get the Coin"] = 2
recs["Mountain Fortress"] = 2
recs["Dark Greens"] = 2
recs["Fizik Who 5"] = 2
recs["A Hell of a Ride"] = 1
recs["Old Town"] = 1
recs["Seasons in the Abyss"] = 1
-- 2023
recs["Spider-Claw"] = 1
recs["Autumn v1.2"] = 2
recs["Cultist Island"] = 1
recs["Cannonballin'"] = 1
recs["Adventurer"] = 2
recs["Mazy Mansions"] = 2
recs["In the Castle"] = 2
recs["The Thousand Towers"] = 2
recs["Fortress Assault"] = 2
recs["Arcana v1.2"] = 2
recs["Jailbreak"] = 2
recs["Underground"] = 2
recs["Christmas Eve Adventure"] = 2
-- 2024
recs["Whiskey in the Jar"] = 2
recs["Walk on Water"] = 2
recs["The Big Treasure Chest"] = 2
recs["The Poisonous Caves"] = 2
recs["Ring of Fire"] = 2
recs["Lava Factory"] = 2

return recs
