local _exef = {
	_BnW                    = ffi.cast("signed int (*)(int)", 0x463C90),
	_RegisterHitHandler     = ffi.cast("int (*__thiscall)(ObjectA*, const char*)", 0x4C7730),
	_RegisterAttackHandler  = ffi.cast("int (*__thiscall)(ObjectA*, const char*)", 0x4C7810),
	_ChangeResolution       = ffi.cast("int (*__thiscall)(int*,int, int)",0x429D80),
	_BlockClaw              = ffi.cast("void (*)()", 0x421450),
	_TextOut                = ffi.cast("int (*__thiscall)(int, const char *)", 0x42C780),
	_KillClaw               = ffi.cast("int (*)(ObjectA*, ObjectV*, void*, int)", 0x418BD0),
	_ClawGivePowerup        = ffi.cast("int (*)(int, int)", 0x420EE0),
	_ClawJump               = ffi.cast("void (*)(ObjectA*,int)", 0x41FC40),
	_SetMusic               = ffi.cast("int (*__thiscall)(int, const char*, int)", 0x4B4ED0),
	_SetMusicSpeed          = ffi.cast("int (*__thiscall)(int*, int, int)", 0x4B55E0),
	_OpenWindow             = ffi.cast("const char** (*)(int*, int, int)", 0x4382F0),
	_JumpToLevel            = ffi.cast("int (*__thiscall)(int*, int)", 0x429890),
	_Physics                = ffi.cast("int (*__thiscall)(int, ObjectA*, int, int, int)", 0x4CC7E0),
	_IsVisible              = ffi.cast("int (*__thiscall)(int, int, int, int, int)", 0x4CE620),
	_AlignToGround          = ffi.cast("int (*__thiscall)(int, ObjectA*, int)", 0x4CE420),
	_CreateObject           = ffi.cast("ObjectA* (*__thiscall)(int, int, int, int, int, const char *, unsigned int)", 0x4C9480),
	_SetImage               = ffi.cast("int (*__thiscall)(ObjectA*, const char*)", 0x4C6DD0),
	_SetAnimation           = ffi.cast("int (*__thiscall)(ObjectA*, const char*, int)", 0x4C6E40),
	_SetImageAndI           = ffi.cast("int (*__thiscall)(ObjectA*, const char*, int)",0x4C6D60),
	_LoadFolder             = ffi.cast("void* (*__thiscall)(int, const char*)",0x4B79D0),
	_LoadAsset              = ffi.cast("int (*__thiscall)(int this, const char*, void**)", 0x4FC6B4),
	_MapSoundsFolder        = ffi.cast("void (*__thiscall)(int, void *, const char *, const char *)",0x4CAE80),
	_MapImagesFolder        = ffi.cast("void (*__thiscall)(int, void *, const char *, const char *)",0x4D0D30),
	_MapAnisFolder          = ffi.cast("void (*__thiscall)(int, void *, const char *, const char *)",0x4CECE0),
	_LoadSingleFile         = ffi.cast("void* (*__thiscall)(void*, const char *, unsigned int)",0x4B5FC0),
	_MapMusicFile           = ffi.cast("int (*__thiscall)(int, void*, int, const char*)",0x4B4DC0),
	_IncludeAssets          = ffi.cast("int (*__thiscall)(int, const char *, int)",0x4B6D50),
	_KeyPressed             = ffi.cast("int (*)(int)",ffi.cast("int*",0x50C438)[0]),
	_PlaySound              = ffi.cast("int (*__thiscall)(void*, int, int, int, int)", 0x421BB0),
	_ClawSound              = ffi.cast("ObjectA* (*)(const char*,int)", 0x48FB00),
	_AnimationStep          = ffi.cast("int (*__thiscall)(void*, unsigned int)", 0x4C8550),
	_CreateGoodie           = ffi.cast("int (*)(int, int, int, int, int)", 0x4751A0),
	_DropMultipleTreasure   = ffi.cast("int (*)(int, int, int, int, int)", 0x40FAA0),
	_GetValueFromRegister   = ffi.cast("int (*__thiscall)(int, const char*, int)",0x4B5950),
	_LoadBaseLevDefaults    = ffi.cast("int (*__cdecl)(int)", 0x454340),
	_DumpScreen             = ffi.cast("int (*__cdecl)(int, int*)", 0x499530),
	_MakeScreenToFile       = ffi.cast("int (*__thiscall)(int, const char*, int, int, int)", 0x4BAA40),
    _SetBgImage             = ffi.cast("int (*__thiscall)(int, const char*, int, int, int, int)",0x492950),
	_TimeThings             = ffi.cast("int* (*__thiscall)(int**)",0x42C3C0),
	-- new in 1.4.5:
	_GetMusic               = ffi.cast("int* (*__thiscall)(int, const char*)", 0x4B4E80), -- (nRes(20), name)
	_GetMusicState          = ffi.cast("int (*__thiscall)(int)", 0x4B55B0), -- (_GetMusic(name))
	_Quake                  = ffi.cast("void (*__cdecl)(int)", 0x48A000), -- (time ms)
	_GetSound               = ffi.cast("int* (*__thiscall)(int, const char*)", 0x4FC6D6), -- (Game(10)+16, name)
	_GetSoundA              = ffi.cast("int* (*__thiscall)(int, const char*)", 0x45A4E0), -- (Game(10), name)
	_StopSound              = ffi.cast("void (*__thiscall)(int)", 0x4B34D0), -- (_GetSoundA(Game(10), name))
	_SetImgFlag             = ffi.cast("void (*__thiscall)(void*, unsigned int)", 0x4CF4C0),
	_SetImgColor            = ffi.cast("void (*__thiscall)(void*, unsigned int)", 0x4CF520),
	_SetImgCLT              = ffi.cast("void (*__thiscall)(void*, int)", 0x4CF560),
    _RandomInt              = ffi.cast("int(*)()", 0x4A595B)
}

return _exef
